using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using Xunit;
using ConvMVVM3.Core.Mvvm;
using ConvMVVM3.Core.Mvvm.Attributes;

namespace ConvMVVM3.Tests
{
    public class SourceGeneratorTests
    {
        [Fact]
        public void GeneratesObservableProperties()
        {
            // Arrange
            var source = @"
using ConvMVVM3.Core.Mvvm.Attributes;
using ConvMVVM3.Core.Mvvm;

namespace TestNamespace
{
    public partial class TestViewModel : ObservableObject
    {
        [ObservableProperty]
        private string _name;
    }
}
";
            var compilation = CreateCompilation(source);
            var generator = new ConvMVVM3.SourceGenerator.ConvMVVM3Generator();

            // Act
            var driver = CSharpGeneratorDriver.Create(generator);
            driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation);
            var result = driver.GetRunResult();

            // Assert
            Assert.Equal(2, result.GeneratedTrees.Length); // AlwaysExecuted.g.cs + TestViewModel_Generated.g.cs
            
            // Find the TestViewModel generated file (not the AlwaysExecuted one)
            var viewModelGeneratedCode = result.GeneratedTrees
                .FirstOrDefault(tree => tree.ToString().Contains("TestViewModel"))?.ToString();
            
            Assert.NotNull(viewModelGeneratedCode);
            Assert.Contains("public string Name", viewModelGeneratedCode);
            Assert.Contains("return _name;", viewModelGeneratedCode);
            Assert.Contains("SetProperty(ref _name, value)", viewModelGeneratedCode);
        }

        [Fact]
        public void GeneratesAsyncRelayCommands()
        {
            // Arrange
            var source = @"
using ConvMVVM3.Core.Mvvm.Attributes;

namespace TestNamespace
{
    public partial class TestViewModel
    {
        [AsyncRelayCommand]
        private async Task LoadDataAsync()
        {
            await Task.Delay(100);
        }
    }
}";
            var compilation = CreateCompilation(source);
            var generator = new ConvMVVM3.SourceGenerator.ConvMVVM3Generator();

            // Act
            var driver = CSharpGeneratorDriver.Create(generator);
            driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation);
            var result = driver.GetRunResult();

            // Assert
            Assert.Equal(2, result.GeneratedTrees.Length); // AlwaysExecuted.g.cs + TestViewModel_Generated.g.cs
            
            // Find TestViewModel generated file
            var viewModelGeneratedCode = result.GeneratedTrees
                .FirstOrDefault(tree => tree.ToString().Contains("TestViewModel"))?.ToString();
            
            Assert.NotNull(viewModelGeneratedCode);
            
            // Let's see what was actually generated by looking for any AsyncRelayCommand
            Assert.Contains("AsyncRelayCommand", viewModelGeneratedCode);
            Assert.Contains("LoadDataAsync", viewModelGeneratedCode);
        }

        [Fact]
        public void GeneratesRelayCommands()
        {
            // Arrange
            var source = @"
using ConvMVVM3.Core.Mvvm.Attributes;

namespace TestNamespace
{
    public partial class TestViewModel
    {
        [RelayCommand]
        private void Save()
        {
            // Save logic
        }
    }
}";
            var compilation = CreateCompilation(source);
            var generator = new ConvMVVM3.SourceGenerator.ConvMVVM3Generator();

            // Act
            var driver = CSharpGeneratorDriver.Create(generator);
            driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation);
            var result = driver.GetRunResult();

            // Assert
            Assert.Equal(2, result.GeneratedTrees.Length); // AlwaysExecuted.g.cs + TestViewModel_Generated.g.cs
            
            // Find TestViewModel generated file
            var viewModelGeneratedCode = result.GeneratedTrees
                .FirstOrDefault(tree => tree.ToString().Contains("TestViewModel"))?.ToString();
            
            Assert.NotNull(viewModelGeneratedCode);
            Assert.Contains("public RelayCommand SaveCommand", viewModelGeneratedCode);
            Assert.Contains("new RelayCommand(Save)", viewModelGeneratedCode);
        }

        [Fact]
        public void GeneratesMixedAttributesCorrectly()
        {
            // Arrange
            var source = @"
using ConvMVVM3.Core.Mvvm.Attributes;

namespace TestNamespace
{
    public partial class TestViewModel
    {
        [ObservableProperty]
        private string _name;
        
        [RelayCommand]
        private void Save()
        {
        }
        
        [AsyncRelayCommand]
        private async Task LoadDataAsync()
        {
            await Task.Delay(100);
        }
    }
}";
            var compilation = CreateCompilation(source);
            var generator = new ConvMVVM3.SourceGenerator.ConvMVVM3Generator();

            // Act
            var driver = CSharpGeneratorDriver.Create(generator);
            driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation);
            var result = driver.GetRunResult();

            // Assert
            Assert.Equal(2, result.GeneratedTrees.Length); // AlwaysExecuted.g.cs + TestViewModel_Generated.g.cs
            
            // Find TestViewModel generated file
            var viewModelGeneratedCode = result.GeneratedTrees
                .FirstOrDefault(tree => tree.ToString().Contains("TestViewModel"))?.ToString();
            
            Assert.NotNull(viewModelGeneratedCode);
            
            // Check ObservableProperty generation
            Assert.Contains("public string Name", viewModelGeneratedCode);
            Assert.Contains("return _name;", viewModelGeneratedCode);
            Assert.Contains("SetProperty(ref _name, value)", viewModelGeneratedCode);
            
            // Check RelayCommand generation
            Assert.Contains("public RelayCommand SaveCommand", viewModelGeneratedCode);
            Assert.Contains("new RelayCommand(Save)", viewModelGeneratedCode);
            
            // Check AsyncRelayCommand generation
            Assert.Contains("AsyncRelayCommand", viewModelGeneratedCode);
            Assert.Contains("LoadDataAsync", viewModelGeneratedCode);
        }



        private static Compilation CreateCompilation(string source)
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(source);
            var references = new[]
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(ConvMVVM3.Core.Mvvm.ObservableObject).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(ObservablePropertyAttribute).Assembly.Location),
            };
            return CSharpCompilation.Create("Test", new[] { syntaxTree }, references, new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        }
    }
}